// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Lib.Domain.Object
{
    public class Employee_Master
    {
        public Employee_Master()
        {
            ItemGroup_CreatedBy_Navigation = new HashSet<ItemGroup>();
            ItemGroup_LastModifiedBy_Navigation = new HashSet<ItemGroup>();
            ItemMaster_CreatedBy_Navigation = new HashSet<ItemMaster>();
            ItemMaster_LastModifiedBy_Navigation = new HashSet<ItemMaster>();
            SupplierMaster_CreatedBy_Navigation = new HashSet<Supplier_Master>();
            SupplierMaster_ModifiedBy_Navigation = new HashSet<Supplier_Master>();
            MRQ_Header_CreatedBy_Navigation = new HashSet<MRQ_Header>();
            MRQ_Header_LastModifiedBy_Navigation = new HashSet<MRQ_Header>();
            PurchaseOrder_Header_CreatedBy_Navigation = new HashSet<PurchaseOrder_Header>();
            PurchaseOrder_HeaderLastModifiedBy_Navigation = new HashSet<PurchaseOrder_Header>();
        }
        public long EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public DateTime? JoinDate { get; set; }
        public string Homephone { get; set; }
        public string Workphone { get; set; }
        public DateTime? DateOfBirth { get; set; }

        //Navigation
        public virtual ICollection<ItemGroup> ItemGroup_CreatedBy_Navigation { get; set; }
        public virtual ICollection<ItemGroup> ItemGroup_LastModifiedBy_Navigation { get; set; }
        public virtual ICollection<ItemMaster> ItemMaster_CreatedBy_Navigation { get; set; }
        public virtual ICollection<ItemMaster> ItemMaster_LastModifiedBy_Navigation { get; set; }
        public virtual ICollection<Supplier_Master> SupplierMaster_CreatedBy_Navigation { get; set; }
        public virtual ICollection<Supplier_Master> SupplierMaster_ModifiedBy_Navigation { get; set; }
        public virtual ICollection<MRQ_Header> MRQ_Header_CreatedBy_Navigation { get; set; }
        public virtual ICollection<MRQ_Header> MRQ_Header_LastModifiedBy_Navigation { get; set; }
        public virtual ICollection<PurchaseOrder_Header> PurchaseOrder_Header_CreatedBy_Navigation { get; set; }
        public virtual ICollection<PurchaseOrder_Header> PurchaseOrder_HeaderLastModifiedBy_Navigation { get; set; }
    }
}